language: node_js

addons:
  firefox: "52.0.2"

services:
  - xvfb

branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+.*/
    - /^rc-.*$/

before_script:
  - "export DISPLAY=:99.0"
  - sleep 3 # give xvfb some time to start

script: npm run ci

after_success:
  - bash <(curl -s https://codecov.io/bash)
